shared workflows for automatically opening PRs on dependency updates
remerge/workflows pull request #32
Opened 2022-07-11 12:23 UTC by joelanders

2022-07-20 18:56 UTC, VOvchinnikov requested changes

2022-07-20 18:56 UTC, VOvchinnikov commented on .github/workflows/handle_possible_dependency_update_event.yml
> +  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
We don't need this manually declared, `webfactory/ssh-agent@v0.5.0` sets it up correctly (other workflows use the running agent too)

2022-07-20 18:56 UTC, VOvchinnikov commented on .github/workflows/handle_possible_dependency_update_event.yml
> +          git diff
Is there any purpose in this command, outside of debugging information?

2022-07-20 18:56 UTC, VOvchinnikov commented on .github/workflows/handle_possible_dependency_update_event.yml
> +          committer: Dependency Updater <noreply@example.com>
`noreply@example.com` here and in the next line

2022-07-20 18:56 UTC, VOvchinnikov commented on .github/workflows/handle_possible_dependency_update_event.yml
> +          token: ${{ secrets.PAT_FOR_UPDATING }}
Name `pat` is quite difficult to parse. Please rename it to something like `gh_token` or the like.

2022-07-20 18:56 UTC, VOvchinnikov commented on .github/workflows/check_repos_i_depend_on.yml
> +name: Check repos I depend on
I am entirely missing a use case that makes this workflow necessary.

This PR https://github.com/remerge/deptest-service/pull/18 sheds little light as well - it basically _always_ creates an event for itself, whenever there's a commit to the repo, because the workflow runs unconditionally always. 

Why is this even necessary? If the only purpose is to check the already open PRs and update/close them, this could be done directly on every commit/push to the listed branches, no need for an extra event for that.

2022-07-25 10:40 UTC, joelanders commented on .github/workflows/handle_possible_dependency_update_event.yml
> +          git diff
`git diff` is just to make the log a bit more informative, yeah.

2022-07-25 10:48 UTC, joelanders commented on .github/workflows/check_repos_i_depend_on.yml
> +name: Check repos I depend on
It actually creates many events for itself: one for every dependency.

The Trello card mentioned a specific case where someone pushes an update to go.mod/go.sum outside of one of the automatic PRs, which could make those PRs unmergeable.

I don't have a way of getting a list of the automatic PRs and looping over them, so I just trigger the "handle possible dependency update" thing for every dependency instead.

2022-07-25 10:52 UTC, joelanders commented on .github/workflows/handle_possible_dependency_update_event.yml
> +          committer: Dependency Updater <noreply@example.com>
:+1:

2022-07-25 10:53 UTC, joelanders commented on .github/workflows/handle_possible_dependency_update_event.yml
> +          token: ${{ secrets.PAT_FOR_UPDATING }}
:+1:

2022-07-25 10:58 UTC, joelanders commented on .github/workflows/handle_possible_dependency_update_event.yml
> +  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
:+1:

2022-07-25 11:02 UTC, joelanders commented
https://github.com/remerge/github/commit/24562f6861a8e8b6d739213353166b8ca0192b2d <- going to reference this new organization-wide token.

2022-07-25 12:17 UTC, VOvchinnikov commented on .github/workflows/check_repos_i_depend_on.yml
> +name: Check repos I depend on
I don't mind the check itself (unless it would cause CI to take super significant time, that is) - I object using an extra event for this.

It can be a normal step, that is triggered on push to `master` - the same code, run on different trigger.

Right now the chain looks like this
"push to master" -> "emit the event" -> run dependencies check step

"emit the event" isn't really necessary.

2022-07-25 12:23 UTC, VOvchinnikov requested changes

2022-07-25 12:23 UTC, VOvchinnikov commented on .github/workflows/check_repos_i_depend_on.yml
> +      pat_for_updating:
It is still called "pat"

2022-07-25 12:23 UTC, VOvchinnikov commented on .github/workflows/notify_repos_that_depend_on_me.yml
> +      pat_for_updating:
It is still called "pat"

2022-07-25 12:23 UTC, VOvchinnikov commented on .github/workflows/handle_possible_dependency_update_event.yml
> +          token: ${{ secrets.DEPUPDATER_GH_TOKEN }}
You can't directly use global secrets in shared workflows, unfortunately, it has to be a `secret` argument

2022-07-25 12:23 UTC, VOvchinnikov commented on .github/workflows/handle_possible_dependency_update_event.yml
> +  repository_dispatch:
This is planned to be used as a shared workflow - for those, you can't provide such an `on` statement AFAIR, only on `workflow_call`.

The condition for event has to be done either in the workflow, that refers this one directly, or inside the workflow step in `if` statement.

2022-07-25 13:12 UTC, joelanders commented on .github/workflows/check_repos_i_depend_on.yml
> +name: Check repos I depend on
Also agree. If this was a reasonable scripting language, I could just call the "handle possible dependency update" "shared workflow" like a function in a for loop.

But (IIRC) you can't call a "shared workflow" within a "matrix strategy" -- you can instead make it a "composite action" but that... broke something else or looked uglier than this. Let me see if I recorded that in a rant somewhere.

2022-07-25 13:18 UTC, joelanders commented on .github/workflows/check_repos_i_depend_on.yml
> +      pat_for_updating:
:+1:

2022-07-25 15:22 UTC, joelanders commented
Alright, here's what it looks like to call into these shared workflows: https://github.com/remerge/deptest-service/tree/main/.github/workflows

2022-07-25 16:35 UTC, joelanders commented
Alright, it _seems to work_ on those three repos in my last comment.

deptest-service depends on deptest-primary.
deptest-primary depends on deptest-secondary.

* update deptest-secondary
* PR gets created in deptest-primary
* ignore that PR, do `go get github.com/remerge/deptest-secondary && go mod tidy`, push directly to main.
* the redundant PR gets closed automatically.
  * only if you don't forget to do `go mod tidy`: otherwise the go.sum files will be different and the PR doesn't look redundant...
* a PR gets created in deptest-service
* smash the merge button
* profit

2022-07-25 16:38 UTC, joelanders commented on .github/workflows/check_repos_i_depend_on.yml
> +name: Check repos I depend on
Maybe tomorrow I'll have another go at the "composite action" approach.

2022-07-26 12:52 UTC, joelanders commented on .github/workflows/check_repos_i_depend_on.yml
> +name: Check repos I depend on
Never mind, it's not worth it.

2022-07-27 10:21 UTC, VOvchinnikov commented on .github/workflows/check_repos_i_depend_on.yml
> +name: Check repos I depend on
I don’t see a matrix strategy call here - could you link it, where matrix strategy is used?

2022-07-27 10:24 UTC, VOvchinnikov commented on .github/workflows/check_repos_i_depend_on.yml
> +name: Check repos I depend on
I specifically checked the way you have been using these workflows - and I cannot find anything that actually prevents you from calling the update workflow as a result of commit event. Could you also please point me there?

2022-07-27 10:52 UTC, joelanders commented on .github/workflows/check_repos_i_depend_on.yml
> +name: Check repos I depend on
this is the matrix strategy:
```yaml
jobs:
  notify-self-about-all-dependencies:
    strategy:
      matrix:   # <-- poor man's for loop
        dependency: ${{ fromJSON(inputs.dependencies) }}  # <-- poor man's list
```

so two things:
* you can't call a "shared workflow" under a matrix strategy. i would need to turn handle_possible_dependency_update.yml into a "composite strategy". i tried that, and it looked worse than the current approach.
* i don't want to only call handle_possible_dependency_update.yml once on a commit event -- i need to call it for every "repo i depend on".

2022-07-27 10:54 UTC, joelanders commented on .github/workflows/notify_repos_that_depend_on_me.yml
> +      pat_for_updating:
:+1:

2022-07-27 10:54 UTC, joelanders commented on .github/workflows/handle_possible_dependency_update_event.yml
> +          token: ${{ secrets.DEPUPDATER_GH_TOKEN }}
:+1:

2022-07-27 10:55 UTC, joelanders commented on .github/workflows/handle_possible_dependency_update_event.yml
> +  repository_dispatch:
:+1:

2022-07-27 10:59 UTC, VOvchinnikov requested changes

2022-07-27 10:59 UTC, VOvchinnikov commented on .github/workflows/check_repos_i_depend_on.yml
> +name: Check repos I depend on
Still changes requested, the question is yet open

2022-07-27 11:00 UTC, joelanders commented on .github/workflows/check_repos_i_depend_on.yml
> +name: Check repos I depend on
i'm lost, which question now?

2022-07-27 11:05 UTC, joelanders commented on .github/workflows/check_repos_i_depend_on.yml
> +name: Check repos I depend on
Let me try the "composite action" again... I remember it being ugly, but triggering fewer events + workflows would also be nice.

2022-07-27 12:02 UTC, VOvchinnikov commented on .github/workflows/check_repos_i_depend_on.yml
> +name: Check repos I depend on
Composite action cannot use secrets in any shape or form, so since you have to interact with GH API via a token, it won't work.

2022-07-27 12:08 UTC, VOvchinnikov submitted a review, later dismissed

2022-07-27 12:08 UTC, VOvchinnikov commented on .github/workflows/check_repos_i_depend_on.yml
> +      uses: joelanders/check-possible-dependency-update@main
Let's not use this composite action: it posts _very_ sensitive information publicly

2022-07-27 17:42 UTC, joelanders commented
Alright, turns out we _do_ like the Composite Action better (fewer triggered workflows, less log spam).

It has to live in its own repo: https://github.com/remerge/check-possible-dependency-update

[Sounds like it _can_ be a private repo](https://github.blog/changelog/2022-03-04-sharing-github-actions-within-your-enterprise-is-now-ga/), but you have to check a box in that repo's settings.

From the web UI, it sounds like it's at

Repo name -> Settings -> Actions -> General -> Access -> check "accessible within organization".

[mineiros, however, says](https://github.com/mineiros-io/terraform-github-repository#module-features):
> Features not yet implemented: Project Columns support, Actions, Repository File

So I'm not sure if that means someone has to check the box from the web UI or whether we have to make the check-possible-dependency-update repo public for now.

2022-07-28 13:59 UTC, joelanders commented on .github/workflows/check_repos_i_depend_on.yml
> +      uses: joelanders/check-possible-dependency-update@main
:+1: we decided out of band that it's ok, actually.

2022-07-28 14:18 UTC, VOvchinnikov approved these changes

2022-07-28 14:22 UTC, VOvchinnikov approved these changes

2022-07-28 14:23 UTC, merged