Core 581
remerge/workflows pull request #91
Opened 2024-03-19 15:29 UTC by tundeaoni

2024-03-19 15:30 UTC, remerge-hal commented
This comment ensures that the correct Slack channel is notified after the team/project label `CORE` has been added to this pull request.

See [this comment](https://remerge.atlassian.net/browse/ITSUP-1973?focusedCommentId=90701) for details.

2024-03-20 11:16 UTC, hollow requested changes

2024-03-20 11:16 UTC, hollow commented on .github/workflows/nomad-pack.yml
> +      op_service_account:
let's rename this to `op_service_account_token`

2024-03-20 11:16 UTC, hollow commented on .github/workflows/nomad-pack.yml
> +          NOMAD_TOKEN: ${{ format('op://{0}', inputs.one_password_secret_path) }}
the `op://` prefix should either be part of the input (and then we can skip the format here) or we change the input to just the item name and hardcode the vault `secrets` as well (the workflows don't have access to any other vault anyway)

2024-03-20 16:55 UTC, tundeaoni commented
@hollow PR has been updated with your suggestions

2024-03-21 10:59 UTC, merged